Index: traceback.txt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.BaseRevisionTextPatchEP
<+>I'm sorry, but an uncaught exception occurred.\r\n\r\nWhile running game code:\r\n  File \"game/script.rpy\", line 22, in script\r\n    '''\r\n  File \"game/script.rpy\", line 22, in script\r\n    '''\r\nKeyError: 'name'\r\n\r\n-- Full Traceback ------------------------------------------------------------\r\n\r\nFull traceback:\r\n  File \"C:\\Users\\Админ\\Downloads\\renpy-8.1.3-sdk\\renpy\\bootstrap.py\", line 275, in bootstrap\r\n    renpy.main.main()\r\n  File \"C:\\Users\\Админ\\Downloads\\renpy-8.1.3-sdk\\renpy\\main.py\", line 670, in main\r\n    run(restart)\r\n  File \"C:\\Users\\Админ\\Downloads\\renpy-8.1.3-sdk\\renpy\\main.py\", line 144, in run\r\n    renpy.execution.run_context(True)\r\n  File \"C:\\Users\\Админ\\Downloads\\renpy-8.1.3-sdk\\renpy\\execution.py\", line 955, in run_context\r\n    context.run()\r\n  File \"game/script.rpy\", line 22, in script\r\n    '''\r\n  File \"/home/tom/ab/renpy-build-fix/tmp/install.linux-x86_64/lib/python3.9/site-packages/future/utils/__init__.py\", line 444, in raise_\r\n  File \"game/script.rpy\", line 22, in script\r\n    '''\r\n  File \"C:\\Users\\Админ\\Downloads\\renpy-8.1.3-sdk\\renpy\\ast.py\", line 930, in execute\r\n    renpy.exports.say(who, what, *args, **kwargs)\r\n  File \"C:\\Users\\Админ\\Downloads\\renpy-8.1.3-sdk\\renpy\\exports.py\", line 1474, in say\r\n    who(what, *args, **kwargs)\r\n  File \"C:\\Users\\Админ\\Downloads\\renpy-8.1.3-sdk\\renpy\\character.py\", line 1337, in __call__\r\n    what = self.prefix_suffix(\"what\", self.what_prefix, what, self.what_suffix)\r\n  File \"C:\\Users\\Админ\\Downloads\\renpy-8.1.3-sdk\\renpy\\character.py\", line 1251, in prefix_suffix\r\n    return (sub(prefix) + sub(body) + sub(suffix))\r\n  File \"C:\\Users\\Админ\\Downloads\\renpy-8.1.3-sdk\\renpy\\character.py\", line 1231, in sub\r\n    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]\r\n  File \"C:\\Users\\Админ\\Downloads\\renpy-8.1.3-sdk\\renpy\\substitutions.py\", line 278, in substitute\r\n    s = formatter.vformat(s, (), kwargs) # type: ignore\r\n  File \"/home/tom/ab/renpy-build-fix/tmp/install.linux-x86_64/lib/python3.9/string.py\", line 165, in vformat\r\n  File \"/home/tom/ab/renpy-build-fix/tmp/install.linux-x86_64/lib/python3.9/string.py\", line 205, in _vformat\r\n  File \"C:\\Users\\Админ\\Downloads\\renpy-8.1.3-sdk\\renpy\\substitutions.py\", line 168, in get_field\r\n    obj, arg_used = super(Formatter, self).get_field(field_name, args, kwargs)\r\n  File \"/home/tom/ab/renpy-build-fix/tmp/install.linux-x86_64/lib/python3.9/string.py\", line 270, in get_field\r\n  File \"/home/tom/ab/renpy-build-fix/tmp/install.linux-x86_64/lib/python3.9/string.py\", line 227, in get_value\r\nKeyError: 'name'\r\n\r\nWindows-10-10.0.19045 AMD64\r\nRen'Py 8.1.3.23091805\r\nproject v1 1.0\r\nMon Oct  2 22:10:53 2023\r\n
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/traceback.txt b/traceback.txt
--- a/traceback.txt	(revision 17f32271243e69a4588d98bf7dd82ad79c683693)
+++ b/traceback.txt	(date 1696418716571)
@@ -1,49 +1,73 @@
 I'm sorry, but an uncaught exception occurred.
 
-While running game code:
-  File "game/script.rpy", line 22, in script
-    '''
-  File "game/script.rpy", line 22, in script
-    '''
-KeyError: 'name'
+While loading <renpy.display.im.Scale object at 0x0000000004fc4490>:
+  File "game/script.rpy", line 28, in script
+    with dissolve
+OSError: Couldn't find file 'second girl/saki/saki_worried/saki_worried.png'.
 
 -- Full Traceback ------------------------------------------------------------
 
 Full traceback:
-  File "C:\Users\Админ\Downloads\renpy-8.1.3-sdk\renpy\bootstrap.py", line 275, in bootstrap
-    renpy.main.main()
-  File "C:\Users\Админ\Downloads\renpy-8.1.3-sdk\renpy\main.py", line 670, in main
-    run(restart)
-  File "C:\Users\Админ\Downloads\renpy-8.1.3-sdk\renpy\main.py", line 144, in run
-    renpy.execution.run_context(True)
-  File "C:\Users\Админ\Downloads\renpy-8.1.3-sdk\renpy\execution.py", line 955, in run_context
-    context.run()
-  File "game/script.rpy", line 22, in script
-    '''
-  File "/home/tom/ab/renpy-build-fix/tmp/install.linux-x86_64/lib/python3.9/site-packages/future/utils/__init__.py", line 444, in raise_
-  File "game/script.rpy", line 22, in script
-    '''
-  File "C:\Users\Админ\Downloads\renpy-8.1.3-sdk\renpy\ast.py", line 930, in execute
-    renpy.exports.say(who, what, *args, **kwargs)
-  File "C:\Users\Админ\Downloads\renpy-8.1.3-sdk\renpy\exports.py", line 1474, in say
-    who(what, *args, **kwargs)
-  File "C:\Users\Админ\Downloads\renpy-8.1.3-sdk\renpy\character.py", line 1337, in __call__
-    what = self.prefix_suffix("what", self.what_prefix, what, self.what_suffix)
-  File "C:\Users\Админ\Downloads\renpy-8.1.3-sdk\renpy\character.py", line 1251, in prefix_suffix
-    return (sub(prefix) + sub(body) + sub(suffix))
-  File "C:\Users\Админ\Downloads\renpy-8.1.3-sdk\renpy\character.py", line 1231, in sub
-    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
-  File "C:\Users\Админ\Downloads\renpy-8.1.3-sdk\renpy\substitutions.py", line 278, in substitute
-    s = formatter.vformat(s, (), kwargs) # type: ignore
-  File "/home/tom/ab/renpy-build-fix/tmp/install.linux-x86_64/lib/python3.9/string.py", line 165, in vformat
-  File "/home/tom/ab/renpy-build-fix/tmp/install.linux-x86_64/lib/python3.9/string.py", line 205, in _vformat
-  File "C:\Users\Админ\Downloads\renpy-8.1.3-sdk\renpy\substitutions.py", line 168, in get_field
-    obj, arg_used = super(Formatter, self).get_field(field_name, args, kwargs)
-  File "/home/tom/ab/renpy-build-fix/tmp/install.linux-x86_64/lib/python3.9/string.py", line 270, in get_field
-  File "/home/tom/ab/renpy-build-fix/tmp/install.linux-x86_64/lib/python3.9/string.py", line 227, in get_value
-KeyError: 'name'
+  File "game/script.rpy", line 28, in script
+    with dissolve
+  File "C:\Users\Админ\Downloads\renpy-8.1.3-sdk\renpy\ast.py", line 1678, in execute
+    renpy.exports.with_statement(trans, paired=paired)
+  File "C:\Users\Админ\Downloads\renpy-8.1.3-sdk\renpy\exports.py", line 1758, in with_statement
+    return renpy.game.interface.do_with(trans, paired, clear=clear)
+  File "C:\Users\Админ\Downloads\renpy-8.1.3-sdk\renpy\display\core.py", line 2978, in do_with
+    return self.interact(trans_pause=True,
+  File "C:\Users\Админ\Downloads\renpy-8.1.3-sdk\renpy\display\core.py", line 3582, in interact
+    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
+  File "C:\Users\Админ\Downloads\renpy-8.1.3-sdk\renpy\display\core.py", line 4175, in interact_core
+    self.draw_screen(root_widget, fullscreen_video, (not fullscreen_video) or video_frame_drawn)
+  File "C:\Users\Админ\Downloads\renpy-8.1.3-sdk\renpy\display\core.py", line 2782, in draw_screen
+    surftree = renpy.display.render.render_screen(
+  File "render.pyx", line 492, in renpy.display.render.render_screen
+  File "render.pyx", line 266, in renpy.display.render.render
+  File "C:\Users\Админ\Downloads\renpy-8.1.3-sdk\renpy\display\layout.py", line 888, in render
+    surf = render(child, width, height, cst, cat)
+  File "render.pyx", line 170, in renpy.display.render.render
+  File "render.pyx", line 266, in renpy.display.render.render
+  File "C:\Users\Админ\Downloads\renpy-8.1.3-sdk\renpy\display\transition.py", line 378, in render
+    top = render(self.new_widget, width, height, st, at)
+  File "render.pyx", line 170, in renpy.display.render.render
+  File "render.pyx", line 266, in renpy.display.render.render
+  File "C:\Users\Админ\Downloads\renpy-8.1.3-sdk\renpy\display\layout.py", line 888, in render
+    surf = render(child, width, height, cst, cat)
+  File "render.pyx", line 170, in renpy.display.render.render
+  File "render.pyx", line 266, in renpy.display.render.render
+  File "C:\Users\Админ\Downloads\renpy-8.1.3-sdk\renpy\display\layout.py", line 888, in render
+    surf = render(child, width, height, cst, cat)
+  File "render.pyx", line 170, in renpy.display.render.render
+  File "render.pyx", line 266, in renpy.display.render.render
+  File "C:\Users\Админ\Downloads\renpy-8.1.3-sdk\renpy\display\transform.py", line 909, in render
+    return RenderTransform(self).render(width, height, st, at)
+  File "accelerator.pyx", line 979, in renpy.display.accelerator.RenderTransform.render
+  File "accelerator.pyx", line 404, in renpy.display.accelerator.RenderTransform.render_child
+  File "render.pyx", line 266, in renpy.display.render.render
+  File "C:\Users\Админ\Downloads\renpy-8.1.3-sdk\renpy\display\image.py", line 513, in render
+    return wrap_render(self.target, width, height, st, at)
+  File "C:\Users\Админ\Downloads\renpy-8.1.3-sdk\renpy\display\image.py", line 316, in wrap_render
+    rend = render(child, w, h, st, at)
+  File "render.pyx", line 170, in renpy.display.render.render
+  File "render.pyx", line 266, in renpy.display.render.render
+  File "C:\Users\Админ\Downloads\renpy-8.1.3-sdk\renpy\display\im.py", line 676, in render
+    return cache.get(self, render=True)
+  File "C:\Users\Админ\Downloads\renpy-8.1.3-sdk\renpy\display\im.py", line 330, in get
+    surf = image.load()
+  File "C:\Users\Админ\Downloads\renpy-8.1.3-sdk\renpy\display\im.py", line 978, in load
+    child = cache.get(self.image)
+  File "C:\Users\Админ\Downloads\renpy-8.1.3-sdk\renpy\display\im.py", line 330, in get
+    surf = image.load()
+  File "C:\Users\Админ\Downloads\renpy-8.1.3-sdk\renpy\display\im.py", line 803, in load
+    raise e
+  File "C:\Users\Админ\Downloads\renpy-8.1.3-sdk\renpy\display\im.py", line 757, in load
+    filelike = renpy.loader.load(self.filename, directory="images")
+  File "C:\Users\Админ\Downloads\renpy-8.1.3-sdk\renpy\loader.py", line 833, in load
+    raise IOError("Couldn't find file '%s'." % name)
+OSError: Couldn't find file 'second girl/saki/saki_worried/saki_worried.png'.
 
 Windows-10-10.0.19045 AMD64
 Ren'Py 8.1.3.23091805
-project v1 1.0
-Mon Oct  2 22:10:53 2023
+Everlasting Semester 1.0
+Wed Oct  4 16:25:16 2023
